In [1]:
import numpy as np


In [3]:
arr =np.array([2,13,432,53])

In [5]:
arr

array([  2,  13, 432,  53])

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.full((2,2),6)

array([[6, 6],
       [6, 6]])

In [15]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [19]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [23]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [31]:
myarr.shape
myarr.size
myarr.ndim


2

In [33]:
myarr.dtype

dtype('int32')

In [35]:
arr =np.array([2,13,432,53],dtype='float32')

In [37]:
arr.dtype

dtype('float32')

In [43]:
n=arr.astype('float64')

In [45]:
arr.dtype

dtype('float32')

In [48]:
n.dtype

dtype('float64')

In [56]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[23,54,67]])

In [58]:
reshaped=myarr.reshape((3,4))

In [60]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 23, 54, 67]])

In [68]:
myarr.reshape((6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 23],
       [54, 67]])

In [70]:
myarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 23, 54, 67])

## indexing and slicing


In [3]:
import numpy as np


In [7]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
flat=arr.flatten()

In [13]:
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
flat[0]


1

In [17]:
flat[3:6]

array([4, 5, 6])

In [19]:
flat[:5] #same as flat[0:5]

array([1, 2, 3, 4, 5])

In [21]:
flat[::2]

array([1, 3, 5, 7, 9])

In [25]:
b=flat[3:7].copy()

In [27]:
b[0]=34

In [29]:
b

array([34,  5,  6,  7])

In [31]:
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr=np.array([1,24,45,643,6,32,63])

In [37]:
arr[[1,4,6]]

array([24,  6, 63])

In [39]:
arr[arr>3]

array([ 24,  45, 643,   6,  32,  63])

In [41]:
arr>24

array([False, False,  True,  True, False,  True,  True])

In [43]:
arr[arr>24]

array([ 45, 643,  32,  63])

## multidimensional Indexing


In [48]:
import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
arr[0]

array([1, 2, 3])

In [52]:
arr[1]

array([4, 5, 6])

In [56]:
print(np.sum(arr,axis=1))

[ 6 15 24]


In [58]:
arr[0][1]

2

In [62]:
arr[0:2,2:3]

array([[3],
       [6]])

In [64]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

(2, 2, 3)


In [66]:
# First sheet, second row, third column
print(arr3D[0, 1, 2])  # Output: 6

print(arr3D[:, 0, :])   # Get the first row from both sheets

6
[[1 2 3]
 [7 8 9]]


In [68]:
arr3D[:,0,:]=0

In [70]:
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])